// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDnaWWduC38z9wCLCRH1LoGR3irKhJBUw',
    appId: '1:249525992953:web:736d7bc4aa73fe78521128',
    messagingSenderId: '249525992953',
    projectId: 'rr-fabrication-456eb',
    authDomain: 'rr-fabrication-456eb.firebaseapp.com',
    storageBucket: 'rr-fabrication-456eb.firebasestorage.app',
    measurementId: 'G-P2XTT7PGQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-BJ5Pwfr2iSa4od0o4oK2LQG4MmE8sU8',
    appId: '1:249525992953:android:954c5d37a68e0647521128',
    messagingSenderId: '249525992953',
    projectId: 'rr-fabrication-456eb',
    storageBucket: 'rr-fabrication-456eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt9WfVb8toXNbD7wi117A6RkiX3fCWwzU',
    appId: '1:249525992953:ios:457ca25756de8792521128',
    messagingSenderId: '249525992953',
    projectId: 'rr-fabrication-456eb',
    storageBucket: 'rr-fabrication-456eb.firebasestorage.app',
    iosClientId: '249525992953-pe2940ug2g2qjcuo5qn1q71qiudroqh7.apps.googleusercontent.com',
    iosBundleId: 'com.example.rrFabrication',
  );
}
